spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/androidproject
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080